In [2]:
import numpy as np

print(np.__version__)

2.5.1



LISTA VS ARRAY

In [2]:
lista = [1, 2, 3, 5]
type(lista)

list

In [3]:
lista * 2

[1, 2, 3, 5, 1, 2, 3, 5]

In [5]:
lista / 2

NameError: name 'lista' is not defined

In [5]:
array = np.array([1, 2, 3, 5])

array * 2

array([ 2,  4,  6, 10])

In [6]:
array / 2

array([0.5, 1. , 1.5, 2.5])

CONVERSION LISTA A NUMPY ARRAY

In [7]:
lista = [1, 2, 3, 5]

arr_lista = np.array(lista)
print(arr_lista)
print(type(arr_lista))

arr_lista * 2

[1 2 3 5]
<class 'numpy.ndarray'>


array([ 2,  4,  6, 10])

In [8]:
arr_lista.dtype

dtype('int64')

In [9]:
lista_decimales = [1.0, 2.1, 2.4, 5.6]
arr_lista = np.array(lista_decimales)
arr_lista.dtype

dtype('float64')

In [10]:
arr_lista = np.array(lista, dtype='float64')
print(arr_lista)
print(arr_lista.dtype)

[1. 2. 3. 5.]
float64


CONVERTIR TIPO DE DATOS DE MI ARRAY

In [12]:
lista = [1, 2, 3, 5]

arr_lista = np.array(lista)
print(arr_lista)
arr_lista.dtype

[1 2 3 5]


dtype('int64')

In [13]:
arr_float = arr_lista.astype('float64')
print(arr_float)
arr_float.dtype

[1. 2. 3. 5.]


dtype('float64')

In [14]:
arr_str = arr_lista.astype('str')
print(arr_str)
arr_str.dtype

['1' '2' '3' '5']


dtype('<U21')

DIMENSIONES

In [15]:
# SCALAR
scalar = np.array(50)
print(scalar)
print(type(scalar))
print(scalar.ndim)

50
<class 'numpy.ndarray'>
0


In [16]:
# VECTOR
vector = np.array([1, 2, 3, 4])
print(vector)
print(vector.ndim)

[1 2 3 4]
1


In [17]:
# MATRIZ
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]]
2


GENERACION DE NUMEROS ALEATORIOS

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [20]:
np.zeros((5, 6), dtype='int64')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
np.ones((10, 10), dtype='int64')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
np.ones((3, 10, 2), dtype='int64')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [23]:

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
x = np.array([250], dtype=np.uint8)
x + 10

array([4], dtype=uint8)

In [3]:
datos = np.random.randn(100)

def pow_datos(datos):
    datos = list(datos)
    return [d ** 2 for d in datos]



# lista = list(range(10000000))
lista_pow = pow_datos(datos)

In [4]:
datos ** 2

array([1.85797026e+00, 4.56981907e-01, 3.28043305e+00, 2.00255696e+00,
       1.09291171e-01, 2.50113520e+00, 8.53159131e+00, 1.52973847e-02,
       1.45915969e-01, 4.83218768e-01, 2.06377797e+00, 2.35106297e+00,
       5.48781142e-01, 3.68725016e+00, 1.54596709e+00, 3.73929531e-02,
       3.21144359e-01, 1.09786188e+00, 1.99536269e-01, 3.18399772e+00,
       3.18205271e-02, 8.51538492e-01, 6.56546745e-01, 1.94955382e+00,
       1.06213020e+00, 1.51734906e-01, 3.63927192e-03, 1.24147838e+00,
       2.66283531e-01, 2.28321465e-02, 3.65066990e+00, 1.47119742e-01,
       2.53749051e-04, 1.34113863e-01, 6.62503157e-01, 1.34463701e+00,
       4.46657803e-01, 9.33048981e-01, 2.16074668e+00, 8.28603328e-02,
       8.40763553e-04, 1.21176956e-01, 3.92626015e-01, 7.95196159e-02,
       8.66411229e-01, 9.82839379e-01, 3.83151194e-01, 6.00690734e-02,
       2.84165612e+00, 5.43902122e-01, 3.00890951e+00, 1.51780079e-02,
       5.07562079e-01, 6.69177560e-01, 1.66409661e-01, 1.27967548e+00,
      